import { useRef } from 'react';
import { Download, Share2, Phone, MapPin, User, Shirt, Heart } from 'lucide-react';
import html2canvas from 'html2canvas';
import './PosterGenerator.css';

export default function PosterGenerator({ data }) {
  const posterRef = useRef();

  const handleDownload = async () => {
    if (!posterRef.current) return;
    try {
      const canvas = await html2canvas(posterRef.current, {
        backgroundColor: '#000',
        scale: 2,
        useCORS: true,
      });
      const link = document.createElement('a');
      link.download = `LostNoMore-${data.child_id}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error('Download failed:', err);
    }
  };

  return (
    <div className="poster-wrapper">
      {/* Printable / shareable poster */}
      <div className="poster-card" ref={posterRef}>
        <div className="poster-header">
          <div className="poster-alert-strip">⚠ EMERGENCY</div>
          <h1 className="poster-headline">FOUND CHILD</h1>
          <p className="poster-urgent">URGENT — NEEDS ASSISTANCE</p>
        </div>

        <div className="poster-body">
          {/* Photo */}
          <div className="poster-photo-col">
            {data.photo ? (
              <img src={data.photo} alt="Found child" className="poster-photo" />
            ) : (
              <div className="poster-photo-placeholder">
                <User size={48} />
                <span>No photo<br/>provided</span>
              </div>
            )}
            <div className="poster-id-badge">{data.child_id}</div>
          </div>

          {/* Details */}
          <div className="poster-details-col">
            <PosterDetail icon={<MapPin size={14} />} label="Found at">
              {data.location}
            </PosterDetail>
            <PosterDetail icon={<Shirt size={14} />} label="Description">
              {data.description}
            </PosterDetail>
            {data.childInfo && (
              <PosterDetail icon={<User size={14} />} label="Child said">
                {data.childInfo}
              </PosterDetail>
            )}
            <PosterDetail icon={<Heart size={14} />} label="Condition">
              {data.condition}
            </PosterDetail>
            <div className="poster-police-block">
              <Phone size={14} />
              <div>
                <div className="poster-police-name">{data.police_contact.station}</div>
                <div className="poster-police-phone">{data.police_contact.phone}</div>
              </div>
            </div>
          </div>
        </div>

        <div className="poster-footer">
          <p>If you have any information, call the police immediately.</p>
          <p className="poster-powered">Generated by LostNoMore • AI-Powered Crisis Response</p>
        </div>
      </div>

      {/* Action buttons */}
      <div className="poster-actions">
        <button className="btn btn-primary" onClick={handleDownload}>
          <Download size={16} /> Download Poster
        </button>
        <button
          className="btn btn-ghost"
          onClick={() => {
            if (navigator.share) {
              navigator.share({ title: 'Found Child — URGENT', text: data.poster.details });
            } else {
              navigator.clipboard.writeText(data.poster.details);
              alert('Poster details copied to clipboard!');
            }
          }}
        >
          <Share2 size={16} /> Share
        </button>
      </div>
    </div>
  );
}

function PosterDetail({ icon, label, children }) {
  return (
    <div className="poster-detail-row">
      <span className="poster-detail-icon">{icon}</span>
      <div>
        <div className="poster-detail-label">{label}</div>
        <div className="poster-detail-value">{children}</div>
      </div>
    </div>
  );
}
